/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author INIONGUN ISAAC I
 */
public class DashboardLeftPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardLeftPanel
     */
    //private final JSplitPane splitPane;
    DashboardFrame frame;
    public DashboardLeftPanel(DashboardFrame frame) {
        initComponents();
        this.frame = frame;
        //this.splitPane = splitPane;
        
        leftAlignButtonContents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnActivateCard = new javax.swing.JButton();
        btnChangeEPKIUserPin = new javax.swing.JButton();
        btnResetUserPinWithMOC = new javax.swing.JButton();
        btnChangeEIDPin = new javax.swing.JButton();
        btnResetEIDPin = new javax.swing.JButton();
        btnManageUser = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        btnCardOperations = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/nimc3.png"))); // NOI18N

        btnActivateCard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActivateCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/activate.png"))); // NOI18N
        btnActivateCard.setText("Activate Card");
        btnActivateCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateCardActionPerformed(evt);
            }
        });

        btnChangeEPKIUserPin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnChangeEPKIUserPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/changeepki.png"))); // NOI18N
        btnChangeEPKIUserPin.setText("Change ePKI User Pin");
        btnChangeEPKIUserPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeEPKIUserPinActionPerformed(evt);
            }
        });

        btnResetUserPinWithMOC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnResetUserPinWithMOC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/changemoc.png"))); // NOI18N
        btnResetUserPinWithMOC.setText("Reset User(ePKI) Pin With MOC");
        btnResetUserPinWithMOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetUserPinWithMOCActionPerformed(evt);
            }
        });

        btnChangeEIDPin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnChangeEIDPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/changeeid.png"))); // NOI18N
        btnChangeEIDPin.setText("Change eID PIN");
        btnChangeEIDPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeEIDPinActionPerformed(evt);
            }
        });

        btnResetEIDPin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnResetEIDPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/unblockeid.png"))); // NOI18N
        btnResetEIDPin.setText("Reset eID PIN");
        btnResetEIDPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetEIDPinActionPerformed(evt);
            }
        });

        btnManageUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnManageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/manageuser.png"))); // NOI18N
        btnManageUser.setText("Manage User");
        btnManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserActionPerformed(evt);
            }
        });

        btnChangePassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/changepassword.png"))); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnSignOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/signout.png"))); // NOI18N
        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        btnCardOperations.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCardOperations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/1393540779_card_chip_gold.png"))); // NOI18N
        btnCardOperations.setText("Card Operations");
        btnCardOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardOperationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActivateCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnChangeEPKIUserPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnResetUserPinWithMOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnChangeEIDPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnResetEIDPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCardOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActivateCard, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangeEPKIUserPin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResetUserPinWithMOC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangeEIDPin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResetEIDPin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCardOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignOut)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivateCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateCardActionPerformed
        // TODO add your handling code here:
        //splitPane.setRightComponent(new ActivateCardPanel());
        //DashboardFrame dashboardFrame = new DashboardFrame();
        changeButtonBackgroundColors(1);
        frame.setSplitPaneRightComponent(1);
    }//GEN-LAST:event_btnActivateCardActionPerformed

    private void btnChangeEPKIUserPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeEPKIUserPinActionPerformed
        // TODO add your handling code here:
        changeButtonBackgroundColors(2);
        frame.setSplitPaneRightComponent(2);
    }//GEN-LAST:event_btnChangeEPKIUserPinActionPerformed

    private void btnResetUserPinWithMOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetUserPinWithMOCActionPerformed
        // TODO add your handling code here:
        changeButtonBackgroundColors(3);
        frame.setSplitPaneRightComponent(3);
    }//GEN-LAST:event_btnResetUserPinWithMOCActionPerformed

    private void btnChangeEIDPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeEIDPinActionPerformed
        // TODO add your handling code here:
        changeButtonBackgroundColors(4);
        frame.setSplitPaneRightComponent(4);
    }//GEN-LAST:event_btnChangeEIDPinActionPerformed

    private void btnResetEIDPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetEIDPinActionPerformed
        // TODO add your handling code here:
        changeButtonBackgroundColors(5);
        frame.setSplitPaneRightComponent(5);
    }//GEN-LAST:event_btnResetEIDPinActionPerformed

    private void btnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserActionPerformed
        // TODO add your handling code here:
        changeButtonBackgroundColors(6);
        frame.setSplitPaneRightComponent(6);
    }//GEN-LAST:event_btnManageUserActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        changeButtonBackgroundColors(7);
        frame.setSplitPaneRightComponent(7);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnCardOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardOperationsActionPerformed
        // TODO add your handling code here:
        changeButtonBackgroundColors(8);
        frame.setSplitPaneRightComponent(8);
    }//GEN-LAST:event_btnCardOperationsActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        
        int confirmCloseOp = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? Note: This will Log you Off!", "Action Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(confirmCloseOp == JOptionPane.YES_OPTION){
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            //getRootPane()
           Window mainFrame = SwingUtilities.windowForComponent(this);
           mainFrame.dispose();
        }
        
    }//GEN-LAST:event_btnSignOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivateCard;
    private javax.swing.JButton btnCardOperations;
    private javax.swing.JButton btnChangeEIDPin;
    private javax.swing.JButton btnChangeEPKIUserPin;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnManageUser;
    private javax.swing.JButton btnResetEIDPin;
    private javax.swing.JButton btnResetUserPinWithMOC;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void changeButtonBackgroundColors(int buttonType) {
        switch(buttonType){
            case 1:
                btnActivateCard.setBackground(Color.white);
                btnChangeEPKIUserPin.setBackground(Color.getHSBColor(240, 240, 240));
                btnResetUserPinWithMOC.setBackground(Color.getHSBColor(240, 240, 240));
                btnChangeEIDPin.setBackground(Color.getHSBColor(240, 240, 240));
                btnResetEIDPin.setBackground(Color.getHSBColor(240, 240, 240));
                btnManageUser.setBackground(Color.getHSBColor(240, 240, 240));
                btnChangePassword.setBackground(Color.getHSBColor(240, 240, 240));
                break;
            case 2:
                btnChangeEPKIUserPin.setBackground(Color.white);
                break;
            case 3:
                btnResetUserPinWithMOC.setBackground(Color.white);
                break;
            case 4:
                btnChangeEIDPin.setBackground(Color.white);
                break;
            case 5:
                btnResetEIDPin.setBackground(Color.white);
                break;
            case 6:
                btnManageUser.setBackground(Color.white);
                break;
            case 7:
                btnChangePassword.setBackground(Color.white);
                break;
            case 8:
                btnCardOperations.setBackground(Color.white);
                break;
        }
    }
    
    private void leftAlignButtonContents(){
        btnActivateCard.setHorizontalAlignment(SwingConstants.LEFT);
        btnCardOperations.setHorizontalAlignment(SwingConstants.LEFT);
        btnChangeEIDPin.setHorizontalAlignment(SwingConstants.LEFT);
        btnChangeEPKIUserPin.setHorizontalAlignment(SwingConstants.LEFT);
        btnChangePassword.setHorizontalAlignment(SwingConstants.LEFT);
        btnManageUser.setHorizontalAlignment(SwingConstants.LEFT);
        btnResetEIDPin.setHorizontalAlignment(SwingConstants.LEFT);
        btnResetUserPinWithMOC.setHorizontalAlignment(SwingConstants.LEFT);
        btnSignOut.setHorizontalAlignment(SwingConstants.LEFT);
    }
}
